# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Customer_New_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Customer_Creation_Form(object):
    def setupUi(self, Customer_Creation_Form):
        Customer_Creation_Form.setObjectName("Customer_Creation_Form")
        Customer_Creation_Form.resize(584, 390)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/images/python_42x42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Customer_Creation_Form.setWindowIcon(icon)
        Customer_Creation_Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Customer_Creation_Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Customer_Creation_Form)
        self.frame.setStyleSheet("#frame QFrame{\n"
"    background-color: #bd93f9;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("color: #f8f8f2;\n"
"background-color: #f8f8f2;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_bar = QtWidgets.QFrame(self.frame_3)
        self.left_bar.setMinimumSize(QtCore.QSize(40, 0))
        self.left_bar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.left_bar.setStyleSheet("background-color: #6272a4;")
        self.left_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_bar.setObjectName("left_bar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_bar)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo = QtWidgets.QFrame(self.left_bar)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.logo.setStyleSheet("background-image: url(:/icons/images/icons/cil-user-follow.png);\n"
"background-repeat: no-repeat;\n"
"background-position: centered;\n"
"background-color: #6272a4;")
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        self.frame_4 = QtWidgets.QFrame(self.left_bar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.left_bar)
        self.central = QtWidgets.QFrame(self.frame_3)
        self.central.setStyleSheet("background-color: #bd93f9;")
        self.central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central.setFrameShadow(QtWidgets.QFrame.Plain)
        self.central.setObjectName("central")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_bar = QtWidgets.QFrame(self.central)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: #6272a4;")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.top_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("padding-left: 10px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.top_bar)
        self.body = QtWidgets.QFrame(self.central)
        self.body.setStyleSheet("QFrame {\n"
"    background-color: #f8f8f2;\n"
"    color: #333;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QLineEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    font: 10pt \"Segoe UI\";\n"
"    color: #f8f8f2;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid #6272a4;\n"
"    border-radius: 5px;    \n"
"    background-color: #6272a4;\n"
"    color: #f8f8f2;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7082b6;\n"
"    border: 2px solid #7082b6;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #546391;\n"
"    border: 2px solid #ff79c6;\n"
"}")
        self.body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body.setFrameShadow(QtWidgets.QFrame.Plain)
        self.body.setObjectName("body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.soldto_num = QtWidgets.QFrame(self.body)
        self.soldto_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.soldto_num.setFrameShadow(QtWidgets.QFrame.Raised)
        self.soldto_num.setObjectName("soldto_num")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.soldto_num)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.cust_code_feild = QtWidgets.QLineEdit(self.soldto_num)
        self.cust_code_feild.setObjectName("cust_code_feild")
        self.gridLayout.addWidget(self.cust_code_feild, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.soldto_num)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.soldto_num)
        self.soldto_name_en = QtWidgets.QFrame(self.body)
        self.soldto_name_en.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.soldto_name_en.setFrameShadow(QtWidgets.QFrame.Raised)
        self.soldto_name_en.setObjectName("soldto_name_en")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.soldto_name_en)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.cust_name_en_feild = QtWidgets.QLineEdit(self.soldto_name_en)
        self.cust_name_en_feild.setObjectName("cust_name_en_feild")
        self.gridLayout_3.addWidget(self.cust_name_en_feild, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.soldto_name_en)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_4.addWidget(self.soldto_name_en)
        self.soldto_name_ru = QtWidgets.QFrame(self.body)
        self.soldto_name_ru.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.soldto_name_ru.setFrameShadow(QtWidgets.QFrame.Raised)
        self.soldto_name_ru.setObjectName("soldto_name_ru")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.soldto_name_ru)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.cust_name_ru_feild = QtWidgets.QLineEdit(self.soldto_name_ru)
        self.cust_name_ru_feild.setObjectName("cust_name_ru_feild")
        self.gridLayout_4.addWidget(self.cust_name_ru_feild, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.soldto_name_ru)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout_4)
        self.verticalLayout_4.addWidget(self.soldto_name_ru)
        self.buttons = QtWidgets.QFrame(self.body)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.buttons)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.buttons)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.soldto_error_lable = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.soldto_error_lable.setFont(font)
        self.soldto_error_lable.setStyleSheet("color: rgb(255, 78, 223);")
        self.soldto_error_lable.setText("")
        self.soldto_error_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.soldto_error_lable.setObjectName("soldto_error_lable")
        self.horizontalLayout_7.addWidget(self.soldto_error_lable)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.buttons)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.save_btn = QtWidgets.QPushButton(self.frame_5)
        self.save_btn.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.save_btn.setFont(font)
        self.save_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_btn.setIcon(icon1)
        self.save_btn.setObjectName("save_btn")
        self.horizontalLayout_8.addWidget(self.save_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.frame_5)
        self.cancel_btn.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/x-octagon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_btn.setIcon(icon2)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout_8.addWidget(self.cancel_btn)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.buttons)
        self.verticalLayout_2.addWidget(self.body)
        self.horizontalLayout_2.addWidget(self.central)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Customer_Creation_Form)
        QtCore.QMetaObject.connectSlotsByName(Customer_Creation_Form)

    def retranslateUi(self, Customer_Creation_Form):
        _translate = QtCore.QCoreApplication.translate
        Customer_Creation_Form.setWindowTitle(_translate("Customer_Creation_Form", "New Customer Form"))
        self.label.setText(_translate("Customer_Creation_Form", "Customer creation"))
        self.label_2.setText(_translate("Customer_Creation_Form", "Sold-To number"))
        self.label_3.setText(_translate("Customer_Creation_Form", "Sold-To name (en)"))
        self.label_4.setText(_translate("Customer_Creation_Form", "Sold-To name (ru)"))
        self.save_btn.setText(_translate("Customer_Creation_Form", "Save"))
        self.cancel_btn.setText(_translate("Customer_Creation_Form", "Cancel"))
import modules.resources_rc
