# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Customer_Filter_screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Customer_Filter_Form(object):
    def setupUi(self, Customer_Filter_Form):
        Customer_Filter_Form.setObjectName("Customer_Filter_Form")
        Customer_Filter_Form.resize(440, 280)
        Customer_Filter_Form.setMinimumSize(QtCore.QSize(0, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/images/images/python_42x42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Customer_Filter_Form.setWindowIcon(icon)
        Customer_Filter_Form.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(Customer_Filter_Form)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(Customer_Filter_Form)
        self.frame.setStyleSheet("#frame QFrame{\n"
"    background-color: #bd93f9;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(2)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("color: #f8f8f2;\n"
"background-color: #f8f8f2;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_bar = QtWidgets.QFrame(self.frame_3)
        self.left_bar.setMinimumSize(QtCore.QSize(40, 0))
        self.left_bar.setMaximumSize(QtCore.QSize(40, 16777215))
        self.left_bar.setStyleSheet("background-color: #6272a4;")
        self.left_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.left_bar.setObjectName("left_bar")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_bar)
        self.verticalLayout_3.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo = QtWidgets.QFrame(self.left_bar)
        self.logo.setMaximumSize(QtCore.QSize(16777215, 30))
        self.logo.setStyleSheet("background-image: url(:/icons/images/icons/filter.svg);\n"
"background-repeat: no-repeat;\n"
"background-position: centered;\n"
"background-color: #6272a4;")
        self.logo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        self.frame_4 = QtWidgets.QFrame(self.left_bar)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3.addWidget(self.frame_4)
        self.horizontalLayout_2.addWidget(self.left_bar)
        self.central = QtWidgets.QFrame(self.frame_3)
        self.central.setStyleSheet("background-color: #bd93f9;")
        self.central.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.central.setFrameShadow(QtWidgets.QFrame.Plain)
        self.central.setObjectName("central")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.central)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.top_bar = QtWidgets.QFrame(self.central)
        self.top_bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.top_bar.setStyleSheet("background-color: #6272a4;")
        self.top_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_bar.setFrameShadow(QtWidgets.QFrame.Plain)
        self.top_bar.setObjectName("top_bar")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_bar)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.top_bar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("padding-left: 10px;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.top_bar)
        self.body = QtWidgets.QFrame(self.central)
        self.body.setStyleSheet("QFrame {\n"
"    background-color: #f8f8f2;\n"
"    color: #333;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"QLineEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    font: 10pt \"Segoe UI\";\n"
"    color: #f8f8f2;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: 2px solid #6272a4;\n"
"    border-radius: 5px;    \n"
"    background-color: #6272a4;\n"
"    color: #f8f8f2;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #7082b6;\n"
"    border: 2px solid #7082b6;\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: #546391;\n"
"    border: 2px solid #ff79c6;\n"
"}")
        self.body.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.body.setFrameShadow(QtWidgets.QFrame.Plain)
        self.body.setObjectName("body")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.body)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.soldto_num = QtWidgets.QFrame(self.body)
        self.soldto_num.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.soldto_num.setFrameShadow(QtWidgets.QFrame.Raised)
        self.soldto_num.setObjectName("soldto_num")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.soldto_num)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.filter_cust_code_feild = QtWidgets.QLineEdit(self.soldto_num)
        self.filter_cust_code_feild.setObjectName("filter_cust_code_feild")
        self.gridLayout.addWidget(self.filter_cust_code_feild, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.soldto_num)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout)
        self.verticalLayout_4.addWidget(self.soldto_num)
        self.buttons = QtWidgets.QFrame(self.body)
        self.buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttons.setObjectName("buttons")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.buttons)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_2 = QtWidgets.QFrame(self.buttons)
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.client_filter_error_lable = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.client_filter_error_lable.setFont(font)
        self.client_filter_error_lable.setStyleSheet("color: rgb(255, 78, 223);")
        self.client_filter_error_lable.setText("")
        self.client_filter_error_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.client_filter_error_lable.setObjectName("client_filter_error_lable")
        self.horizontalLayout_7.addWidget(self.client_filter_error_lable)
        self.verticalLayout_5.addWidget(self.frame_2)
        self.frame_5 = QtWidgets.QFrame(self.buttons)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.client_filter_btn = QtWidgets.QPushButton(self.frame_5)
        self.client_filter_btn.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.client_filter_btn.setFont(font)
        self.client_filter_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/search.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_filter_btn.setIcon(icon1)
        self.client_filter_btn.setObjectName("client_filter_btn")
        self.horizontalLayout_8.addWidget(self.client_filter_btn)
        self.client_filter_cancel_btn = QtWidgets.QPushButton(self.frame_5)
        self.client_filter_cancel_btn.setMaximumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.client_filter_cancel_btn.setFont(font)
        self.client_filter_cancel_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/x-octagon.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.client_filter_cancel_btn.setIcon(icon2)
        self.client_filter_cancel_btn.setObjectName("client_filter_cancel_btn")
        self.horizontalLayout_8.addWidget(self.client_filter_cancel_btn)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.verticalLayout_4.addWidget(self.buttons)
        self.verticalLayout_2.addWidget(self.body)
        self.horizontalLayout_2.addWidget(self.central)
        self.verticalLayout.addWidget(self.frame_3)
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Customer_Filter_Form)
        QtCore.QMetaObject.connectSlotsByName(Customer_Filter_Form)

    def retranslateUi(self, Customer_Filter_Form):
        _translate = QtCore.QCoreApplication.translate
        Customer_Filter_Form.setWindowTitle(_translate("Customer_Filter_Form", "Customer Filter Form"))
        self.label.setText(_translate("Customer_Filter_Form", "Customer Filter Form"))
        self.label_2.setText(_translate("Customer_Filter_Form", "Sold-To number"))
        self.client_filter_btn.setText(_translate("Customer_Filter_Form", "Find"))
        self.client_filter_cancel_btn.setText(_translate("Customer_Filter_Form", "Cancel"))
import modules.resources_rc
