import pandas as pd
from PyQt5 import QtWidgets, QtGui, QtCore
from PyQt5.Qt import *
from PyQt5.QtWidgets import QFileDialog

db_path = 'modules/Bonus_db.db'


class Products_Functions(QtWidgets.QWidget):
    def __init__(self):
        super(Products_Functions, self).__init__()

        self.product_data_page = QtWidgets.QWidget(self)
        self.product_data_page.resize(1058, 631)

        self.product_data_page.setStyleSheet("QPushButton {\n"
                                             "    border: 2px solid #6272a4;\n"
                                             "    border-radius: 5px;\n"
                                             "    background-color: #6272a4;\n"
                                             "    color: #f8f8f2;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:hover {\n"
                                             "    background-color: #bd93f9;\n"
                                             "    border: 2px solid #7082b6;\n"
                                             "}\n"
                                             "\n"
                                             "QPushButton:pressed {\n"
                                             "    background-color: #ff79c6;\n"
                                             "    border: 2px solid #ff79c6;\n"
                                             "}\n"
                                             "\n"
                                             " QLineEdit {\n"
                                             "    background-color: #6272a4;\n"
                                             "    border-radius: 5px;\n"
                                             "    border: 2px solid #6272a4;\n"
                                             "    padding-left: 10px;\n"
                                             "    selection-color: rgb(255, 255, 255);\n"
                                             "    selection-background-color: rgb(255, 121, 198);\n"
                                             "    color: #f8f8f2;\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:hover {\n"
                                             "    border: 2px solid #bd93f9;\n"
                                             "}\n"
                                             "\n"
                                             "QLineEdit:focus {\n"
                                             "    border: 2px solid #ff79c6;\n"
                                             "}")
        self.product_data_page.setObjectName("product_data_page")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.product_data_page)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.row_1 = QtWidgets.QFrame(self.product_data_page)
        self.row_1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.row_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_1.setObjectName("row_1")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.row_1)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.row_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_11.addWidget(self.label_5, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.row_1)
        self.row_2 = QtWidgets.QFrame(self.product_data_page)
        self.row_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_2.setObjectName("row_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.row_2)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.prod_frame = QtWidgets.QFrame(self.row_2)
        self.prod_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.prod_frame.setStyleSheet("")
        self.prod_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prod_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prod_frame.setObjectName("prod_frame")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.prod_frame)
        self.verticalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.prod_heade_frame = QtWidgets.QFrame(self.prod_frame)
        self.prod_heade_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.prod_heade_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.prod_heade_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prod_heade_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prod_heade_frame.setObjectName("prod_heade_frame")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.prod_heade_frame)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label_6 = QtWidgets.QLabel(self.prod_heade_frame)
        self.label_6.setMinimumSize(QtCore.QSize(0, 50))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        self.label_6.setFont(font)
        self.label_6.setText("")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_8.addWidget(self.label_6, 0, 0, 1, 1)
        self.verticalLayout_28.addLayout(self.gridLayout_8)
        self.verticalLayout_25.addWidget(self.prod_heade_frame)
        self.prod_body_frame = QtWidgets.QFrame(self.prod_frame)
        self.prod_body_frame.setMaximumSize(QtCore.QSize(16777215, 1054))
        self.prod_body_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prod_body_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prod_body_frame.setObjectName("prod_body_frame")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.prod_body_frame)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_9.setSpacing(9)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.prod_filter_btn = QtWidgets.QPushButton(self.prod_body_frame)
        self.prod_filter_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.prod_filter_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prod_filter_btn.setFont(font)
        self.prod_filter_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/filter.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prod_filter_btn.setIcon(icon4)
        self.prod_filter_btn.setObjectName("prod_filter_btn")
        self.gridLayout_9.addWidget(self.prod_filter_btn, 0, 1, 1, 1)
        self.prod_update_btn = QtWidgets.QPushButton(self.prod_body_frame)
        self.prod_update_btn.setMinimumSize(QtCore.QSize(0, 30))
        self.prod_update_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prod_update_btn.setFont(font)
        self.prod_update_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-reload.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prod_update_btn.setIcon(icon5)
        self.prod_update_btn.setObjectName("prod_update_btn")
        self.gridLayout_9.addWidget(self.prod_update_btn, 0, 0, 1, 1)
        self.verticalLayout_29.addLayout(self.gridLayout_9)
        self.frame_10 = QtWidgets.QFrame(self.prod_body_frame)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_10.setFont(font)
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_22.setContentsMargins(2, 2, 2, 2)
        self.horizontalLayout_22.setSpacing(2)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.prod_error_lable = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prod_error_lable.setFont(font)
        self.prod_error_lable.setText("")
        self.prod_error_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.prod_error_lable.setObjectName("prod_error_lable")
        self.horizontalLayout_22.addWidget(self.prod_error_lable)
        self.verticalLayout_29.addWidget(self.frame_10)
        self.prod_table_frame = QtWidgets.QFrame(self.prod_body_frame)
        self.prod_table_frame.setMinimumSize(QtCore.QSize(1050, 398))
        self.prod_table_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.prod_table_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.prod_table_frame.setObjectName("prod_table_frame")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.prod_table_frame)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.prod_table = QtWidgets.QTableWidget(self.prod_table_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prod_table.sizePolicy().hasHeightForWidth())
        self.prod_table.setSizePolicy(sizePolicy)
        self.prod_table.setMinimumSize(QtCore.QSize(510, 250))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(51, 51, 51))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.prod_table.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prod_table.setFont(font)
        self.prod_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.prod_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.prod_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.prod_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.prod_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.prod_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.prod_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.prod_table.setShowGrid(True)
        self.prod_table.setGridStyle(QtCore.Qt.SolidLine)
        self.prod_table.setRowCount(0)
        self.prod_table.setColumnCount(13)
        self.prod_table.setObjectName("prod_table")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.prod_table.setHorizontalHeaderItem(12, item)
        self.prod_table.horizontalHeader().setVisible(True)
        self.prod_table.horizontalHeader().setCascadingSectionResizes(True)
        self.prod_table.horizontalHeader().setDefaultSectionSize(110)
        self.prod_table.horizontalHeader().setStretchLastSection(True)
        self.prod_table.verticalHeader().setVisible(False)
        self.prod_table.verticalHeader().setCascadingSectionResizes(False)
        self.prod_table.verticalHeader().setDefaultSectionSize(30)
        self.prod_table.verticalHeader().setHighlightSections(False)
        self.prod_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_23.addWidget(self.prod_table)
        self.verticalLayout_29.addWidget(self.prod_table_frame)
        self.verticalLayout_25.addWidget(self.prod_body_frame)
        self.horizontalLayout_12.addWidget(self.prod_frame)
        self.verticalLayout.addWidget(self.row_2)
        self.row_3 = QtWidgets.QFrame(self.product_data_page)
        self.row_3.setMinimumSize(QtCore.QSize(1050, 60))
        self.row_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.row_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_3.setObjectName("row_3")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.row_3)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_8 = QtWidgets.QFrame(self.row_3)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.prod_file_path_lable = QtWidgets.QLabel(self.frame_8)
        self.prod_file_path_lable.setMinimumSize(QtCore.QSize(0, 30))
        self.prod_file_path_lable.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prod_file_path_lable.setFont(font)
        self.prod_file_path_lable.setStyleSheet("background-color: #6272a4;\n"
                                                "border-radius: 5px;\n"
                                                "border: 2px solid #6272a4;\n"
                                                "padding-left: 10px;\n"
                                                "selection-color: rgb(255, 255, 255);\n"
                                                "selection-background-color: rgb(255, 121, 198);\n"
                                                "color: #f8f8f2;\n"
                                                "")
        self.prod_file_path_lable.setObjectName("prod_file_path_lable")
        self.horizontalLayout_21.addWidget(self.prod_file_path_lable)
        self.horizontalLayout_11.addWidget(self.frame_8)
        self.frame_7 = QtWidgets.QFrame(self.row_3)
        self.frame_7.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.open_prod_file_btn = QtWidgets.QPushButton(self.frame_7)
        self.open_prod_file_btn.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.open_prod_file_btn.setFont(font)
        self.open_prod_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_prod_file_btn.setIcon(icon6)
        self.open_prod_file_btn.setObjectName("open_prod_file_btn")
        self.horizontalLayout_20.addWidget(self.open_prod_file_btn)
        self.horizontalLayout_11.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.row_3)
        self.frame_9.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.upload_prod_file_btn = QtWidgets.QPushButton(self.frame_9)
        self.upload_prod_file_btn.setMinimumSize(QtCore.QSize(90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.upload_prod_file_btn.setFont(font)
        self.upload_prod_file_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icons/images/icons/upload.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_prod_file_btn.setIcon(icon7)
        self.upload_prod_file_btn.setObjectName("upload_prod_file_btn")
        self.horizontalLayout_9.addWidget(self.upload_prod_file_btn)
        self.horizontalLayout_11.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.row_3)