# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from modules.Customer_Data_screen import SoldTo_Functions
from modules.Product_Data_screen import Products_Functions


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1160, 748)
        MainWindow.setMinimumSize(QtCore.QSize(1160, 748))
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-folder-open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"\n"
"SET APP STYLESHEET - FULL STYLES HERE\n"
"LIGHT THEME - DRACULA COLOR BASED\n"
"\n"
"# BY: WANDERSON M.PIMENTA\n"
"# PROJECT MADE WITH: Qt Designer and PySide6\n"
"# V: 1.0.0\n"
"#\n"
"# This project can be used freely for all uses, as long as they maintain the\n"
"# respective credits only in the Python scripts, any information in the visual\n"
"# interface (GUI) can be modified without any implication.\n"
"#\n"
"# There are limitations on Qt licenses if you want to use your products\n"
"# commercially, I recommend reading them on the official website:\n"
"# https://doc.qt.io/qtforpython/licenses.html\n"
"\n"
"///////////////////////////////////////////////////////////////////////////////////////////////// */\n"
"\n"
"QWidget{\n"
"    color: #333;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Tooltip */\n"
"QToolTip {\n"
"    color: #333;\n"
"    background-color: #f8f8f2;\n"
"    border: 1px solid #CCC;\n"
"    background-image: none;\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 2px solid rgb(255, 121, 198);\n"
"    text-align: left;\n"
"    padding-left: 8px;\n"
"    margin: 0px;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Bg App */\n"
"#bgApp {    \n"
"    background-color: #f8f8f2;\n"
"    border: 1px solid #CCC;\n"
"    color: #44475a;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Left Menu */\n"
"#leftMenuBg {    \n"
"    background-color: #6272a4;\n"
"}\n"
"#topLogo {\n"
"    background-color: #6272a4;\n"
"    background-image: url(:/images/images/images/shell_logo.png);\n"
"    background-position: centered;\n"
"    background-repeat: no-repeat;\n"
"}\n"
"#titleLeftApp { font: 63 12pt \"Segoe UI Semibold\"; color: #f8f8f2; }\n"
"#titleLeftDescription { font: 8pt \"Segoe UI\"; color: #bd93f9; }\n"
"\n"
"/* MENUS */\n"
"#topMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#topMenu .QPushButton:hover {\n"
"    background-color: #bd93f9;\n"
"}\n"
"#topMenu .QPushButton:pressed {    \n"
"    background-color: #ff79c6;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#bottomMenu .QPushButton {    \n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#bottomMenu .QPushButton:hover {\n"
"    background-color: #bd93f9;\n"
"}\n"
"#bottomMenu .QPushButton:pressed {    \n"
"    background-color: #ff79c6;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenuFrame{\n"
"    border-top: 3px solid #6a7cb1;\n"
"}\n"
"\n"
"/* Toggle Button */\n"
"#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-color: #5b6996;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: #bd93f9;\n"
"}\n"
"#toggleButton:pressed {    \n"
"    background-color: #ff79c6;\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* Title Menu */\n"
"#titleRightInfo { padding-left: 10px; }\n"
"\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Extra Tab */\n"
"#extraLeftBox {    \n"
"    background-color: #495474;\n"
"    color: #f8f8f2;\n"
"}\n"
"#extraTopBg{    \n"
"    background-color: rgb(189, 147, 249)\n"
"}\n"
"\n"
"/* Icon */\n"
"#extraIcon {\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    background-image: url(:/icons/images/icons/icon_settings.png);\n"
"}\n"
"\n"
"/* Label */\n"
"#extraLabel { color: rgb(255, 255, 255); }\n"
"\n"
"/* Btn Close */\n"
"#extraCloseColumnBtn { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#extraCloseColumnBtn:hover { background-color: rgb(196, 161, 249); border-style: solid; border-radius: 4px; }\n"
"#extraCloseColumnBtn:pressed { background-color: rgb(180, 141, 238); border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Extra Content */\n"
"#extraContent{\n"
"    border-top: 3px solid #6272a4;\n"
"}\n"
"\n"
"/* Extra Top Menus */\n"
"#extraTopMenu .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#extraTopMenu .QPushButton:hover {\n"
"    background-color: #5d6c99;\n"
"}\n"
"#extraTopMenu .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Content App */\n"
"#contentTopBg{    \n"
"    background-color: #6272a4;\n"
"}\n"
"#contentBottom{\n"
"    border-top: 3px solid #bd93f9;\n"
"}\n"
"#titleRightInfo{\n"
"    color: #f8f8f2;\n"
"}\n"
"\n"
"/* Top Buttons */\n"
"#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#rightButtons .QPushButton:hover { background-color: #bd93f9; border-style: solid; border-radius: 4px; }\n"
"#rightButtons .QPushButton:pressed { background-color: #ff79c6; border-style: solid; border-radius: 4px; }\n"
"\n"
"/* Theme Settings */\n"
"#extraRightBox { background-color: #495474; }\n"
"#themeSettingsTopDetail { background-color: #6272a4; }\n"
"\n"
"/* Bottom Bar */\n"
"#bottomBar { background-color: #495474 }\n"
"#bottomBar QLabel { font-size: 11px; color: #f8f8f2; padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }\n"
"\n"
"/* CONTENT SETTINGS */\n"
"/* MENUS */\n"
"#contentSettings .QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color:transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: #f8f8f2;\n"
"}\n"
"#contentSettings .QPushButton:hover {\n"
"    background-color: #5d6c99;\n"
"}\n"
"#contentSettings .QPushButton:pressed {    \n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"QTableWidget */\n"
"QTableWidget {    \n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: #9faeda;\n"
"    outline: none;\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: #9faeda;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: #9faeda;\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"    color: #f8f8f2;\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: #6272a4;\n"
"    max-width: 30px;\n"
"    border: none;\n"
"    border-style: none;\n"
"}\n"
"QTableWidget::horizontalHeader {    \n"
"    background-color: #6272a4;\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid #6272a4;\n"
"    background-color: #6272a4;\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"    color: #f8f8f2;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid #6272a4;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"LineEdit */\n"
"QLineEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    color: #f8f8f2;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"PlainTextEdit */\n"
"QPlainTextEdit {\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"    color: #f8f8f2;\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid #ff79c6;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ScrollBars */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"    height: 8px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background-color: #6272a4;\n"
"    width: 8px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: #6272a4;\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: #6272a4;\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CheckBox */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid #6272a4;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: #6272a4;\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(119, 136, 187);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid #bd93f9;\n"
"    border: 3px solid #bd93f9;    \n"
"    background-image: url(:/icons/images/icons/cil-check-alt.png);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"RadioButton */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid #6272a4;\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: #6272a4;\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(119, 136, 187);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid #bd93f9;\n"
"    border: 3px solid #bd93f9;    \n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"ComboBox */\n"
"QComboBox{\n"
"    background-color: #6272a4;\n"
"    border-radius: 5px;\n"
"    border: 2px solid #6272a4;\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"    color: #f8f8f2;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid #7284b9;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 25px; \n"
"    border-left-width: 3px;\n"
"    border-left-color: #6272a4;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;    \n"
"    background-image: url(:/icons/images/icons/cil-arrow-bottom.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
" }\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(255, 121, 198);    \n"
"    background-color: #6272a4;\n"
"    padding: 10px;\n"
"    selection-background-color: #6272a4;\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"Sliders */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 5px;\n"
"    height: 10px;\n"
"    margin: 0px;\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 5px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: #6272a4;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(189, 147, 249);\n"
"    border: none;\n"
"    height: 10px;\n"
"    width: 10px;\n"
"    margin: 0px;\n"
"    border-radius: 5px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(195, 155, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(255, 121, 198);\n"
"}\n"
"\n"
"/* /////////////////////////////////////////////////////////////////////////////////////////////////\n"
"CommandLinkButton */\n"
"#pagesContainer QCommandLinkButton {    \n"
"    color: rgb(255, 121, 198);\n"
"    border-radius: 5px;\n"
"    padding: 5px;\n"
"    border: 2px solid #ff79c6;\n"
"    color: #ff79c6;\n"
"}\n"
"#pagesContainer QCommandLinkButton:hover {    \n"
"    color: rgb(255, 170, 255);\n"
"    background-color: #6272a4;\n"
"}\n"
"#pagesContainer QCommandLinkButton:pressed {    \n"
"    color: rgb(189, 147, 249);\n"
"    background-color: #586796;\n"
"}\n"
"\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.appMargins = QtWidgets.QVBoxLayout(self.styleSheet)
        self.appMargins.setContentsMargins(10, 10, 10, 10)
        self.appMargins.setSpacing(0)
        self.appMargins.setObjectName("appMargins")
        self.bgApp = QtWidgets.QFrame(self.styleSheet)
        self.bgApp.setStyleSheet("")
        self.bgApp.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(self.bgApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.topLogo = QtWidgets.QFrame(self.topLogoInfo)
        self.topLogo.setGeometry(QtCore.QRect(10, 5, 42, 42))
        self.topLogo.setMinimumSize(QtCore.QSize(42, 42))
        self.topLogo.setMaximumSize(QtCore.QSize(42, 42))
        self.topLogo.setStyleSheet("background-image: url(:/images/images/images/python_42x42.png);")
        self.topLogo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topLogo.setObjectName("topLogo")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(self.leftMenuBg)
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.toggleBox = QtWidgets.QFrame(self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleButton = QtWidgets.QPushButton(self.toggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toggleButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toggleButton.setStyleSheet("background-image: url(:/icons/images/icons/icon_menu.png);")
        self.toggleButton.setObjectName("toggleButton")
        self.verticalLayout_4.addWidget(self.toggleButton)
        self.verticalMenuLayout.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.topMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_home = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_home.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_home.setStyleSheet("background-image: url(:/icons/images/icons/cil-home.png);")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_8.addWidget(self.btn_home)
        self.btn_bonuses = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_bonuses.sizePolicy().hasHeightForWidth())
        self.btn_bonuses.setSizePolicy(sizePolicy)
        self.btn_bonuses.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_bonuses.setFont(font)
        self.btn_bonuses.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_bonuses.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_bonuses.setStyleSheet("background-image: url(:/icons/images/icons/gift.svg);")
        self.btn_bonuses.setObjectName("btn_bonuses")
        self.verticalLayout_8.addWidget(self.btn_bonuses)
        self.btn_invoices = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_invoices.sizePolicy().hasHeightForWidth())
        self.btn_invoices.setSizePolicy(sizePolicy)
        self.btn_invoices.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_invoices.setFont(font)
        self.btn_invoices.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_invoices.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_invoices.setStyleSheet("background-image: url(:/icons/images/icons/cil-featured-playlist.png);")
        self.btn_invoices.setObjectName("btn_invoices")
        self.verticalLayout_8.addWidget(self.btn_invoices)
        self.btn_customers = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_customers.sizePolicy().hasHeightForWidth())
        self.btn_customers.setSizePolicy(sizePolicy)
        self.btn_customers.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_customers.setFont(font)
        self.btn_customers.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_customers.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_customers.setStyleSheet("background-image: url(:/icons/images/icons/cil-people.png);")
        self.btn_customers.setObjectName("btn_customers")
        self.verticalLayout_8.addWidget(self.btn_customers)
        self.btn_products = QtWidgets.QPushButton(self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_products.sizePolicy().hasHeightForWidth())
        self.btn_products.setSizePolicy(sizePolicy)
        self.btn_products.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.btn_products.setFont(font)
        self.btn_products.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_products.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.btn_products.setStyleSheet("background-image: url(:/icons/images/icons/cil-cart.png);")
        self.btn_products.setObjectName("btn_products")
        self.verticalLayout_8.addWidget(self.btn_products)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignTop)
        self.bottomMenu = QtWidgets.QFrame(self.leftMenuFrame)
        self.bottomMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomMenu.setObjectName("bottomMenu")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.bottomMenu)
        self.verticalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.verticalMenuLayout.addWidget(self.bottomMenu, 0, QtCore.Qt.AlignBottom)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.contentBox = QtWidgets.QFrame(self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settingsTopBtn = QtWidgets.QPushButton(self.rightButtons)
        self.settingsTopBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setMaximumSize(QtCore.QSize(28, 16777215))
        self.settingsTopBtn.setStyleSheet("")
        self.settingsTopBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingsTopBtn.setIcon(icon)
        self.settingsTopBtn.setIconSize(QtCore.QSize(20, 20))
        self.settingsTopBtn.setObjectName("settingsTopBtn")
        self.horizontalLayout_2.addWidget(self.settingsTopBtn)
        self.minimizeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeAppBtn.setIcon(icon1)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.maximizeRestoreAppBtn.setIcon(icon2)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeAppBtn.setIcon(icon3)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(self.contentBox)
        self.contentBottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pagesContainer = QtWidgets.QFrame(self.content)
        self.pagesContainer.setStyleSheet("")
        self.pagesContainer.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.pagesContainer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pagesContainer.setObjectName("pagesContainer")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.pagesContainer)
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(self.pagesContainer)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background-image: url(:/images/images/images/python_220x220.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.home.setObjectName("home")
        self.stackedWidget.addWidget(self.home)

        self.product_data_page = Products_Functions()
        self.stackedWidget.addWidget(self.product_data_page)

        self.bonus_data_page = QtWidgets.QWidget()
        self.bonus_data_page.setStyleSheet("QPushButton {\n"
                                           "    border: 2px solid #6272a4;\n"
                                           "    border-radius: 5px;    \n"
                                           "    background-color: #6272a4;\n"
                                           "    color: #f8f8f2;\n"
                                           "}\n"
                                           "QPushButton:hover {\n"
                                           "    background-color: #bd93f9;\n"
                                           "    border: 2px solid #7082b6;\n"
                                           "}\n"
                                           "QPushButton:pressed {    \n"
                                           "    background-color: #ff79c6;\n"
                                           "    border: 2px solid #ff79c6;\n"
                                           "}")
        self.bonus_data_page.setObjectName("bonus_data_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.bonus_data_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.row_6 = QtWidgets.QFrame(self.bonus_data_page)
        self.row_6.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        self.row_6.setFont(font)
        self.row_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_6.setObjectName("row_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.row_6)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.row_6)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_10.addWidget(self.label_4)
        self.verticalLayout_5.addWidget(self.row_6)
        self.row_7 = QtWidgets.QFrame(self.bonus_data_page)
        self.row_7.setMinimumSize(QtCore.QSize(0, 100))
        self.row_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.row_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_7.setObjectName("row_7")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.row_7)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_7.setSpacing(10)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.bonus_list_edit_btn = QtWidgets.QPushButton(self.row_7)
        self.bonus_list_edit_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.bonus_list_edit_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bonus_list_edit_btn.setFont(font)
        self.bonus_list_edit_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icons/images/icons/edit-3.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bonus_list_edit_btn.setIcon(icon8)
        self.bonus_list_edit_btn.setObjectName("bonus_list_edit_btn")
        self.gridLayout_7.addWidget(self.bonus_list_edit_btn, 1, 3, 1, 1)
        self.bonus_list_new_btn = QtWidgets.QPushButton(self.row_7)
        self.bonus_list_new_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.bonus_list_new_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bonus_list_new_btn.setFont(font)
        self.bonus_list_new_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/images/icons/plus.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bonus_list_new_btn.setIcon(icon9)
        self.bonus_list_new_btn.setObjectName("bonus_list_new_btn")
        self.gridLayout_7.addWidget(self.bonus_list_new_btn, 1, 2, 1, 1)
        self.bonus_list_filter_btn = QtWidgets.QPushButton(self.row_7)
        self.bonus_list_filter_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.bonus_list_filter_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bonus_list_filter_btn.setFont(font)
        self.bonus_list_filter_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bonus_list_filter_btn.setIcon(icon4)
        self.bonus_list_filter_btn.setObjectName("bonus_list_filter_btn")
        self.gridLayout_7.addWidget(self.bonus_list_filter_btn, 1, 0, 1, 1)
        self.bonus_list_down_btn = QtWidgets.QPushButton(self.row_7)
        self.bonus_list_down_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.bonus_list_down_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bonus_list_down_btn.setFont(font)
        self.bonus_list_down_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icons/images/icons/download.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bonus_list_down_btn.setIcon(icon10)
        self.bonus_list_down_btn.setObjectName("bonus_list_down_btn")
        self.gridLayout_7.addWidget(self.bonus_list_down_btn, 1, 1, 1, 1)
        self.bonus_list_del_btn = QtWidgets.QPushButton(self.row_7)
        self.bonus_list_del_btn.setMinimumSize(QtCore.QSize(120, 30))
        self.bonus_list_del_btn.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.bonus_list_del_btn.setFont(font)
        self.bonus_list_del_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icons/images/icons/trash-2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bonus_list_del_btn.setIcon(icon11)
        self.bonus_list_del_btn.setObjectName("bonus_list_del_btn")
        self.gridLayout_7.addWidget(self.bonus_list_del_btn, 1, 4, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.row_7)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_7.addWidget(self.frame_2, 0, 2, 1, 1)
        self.horizontalLayout_14.addLayout(self.gridLayout_7)
        self.verticalLayout_5.addWidget(self.row_7)
        self.row_8 = QtWidgets.QFrame(self.bonus_data_page)
        self.row_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.row_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.row_8.setObjectName("row_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.row_8)
        self.horizontalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.bonus_table = QtWidgets.QTableWidget(self.row_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.bonus_table.setFont(font)
        self.bonus_table.setStyleSheet("background: transparent;")
        self.bonus_table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bonus_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.bonus_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.bonus_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bonus_table.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.bonus_table.setObjectName("bonus_table")
        self.bonus_table.setColumnCount(8)
        self.bonus_table.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.bonus_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.bonus_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.bonus_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.bonus_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(10)
        item.setFont(font)
        self.bonus_table.setHorizontalHeaderItem(7, item)
        self.bonus_table.horizontalHeader().setCascadingSectionResizes(True)
        self.bonus_table.horizontalHeader().setDefaultSectionSize(125)
        self.bonus_table.horizontalHeader().setSortIndicatorShown(False)
        self.bonus_table.horizontalHeader().setStretchLastSection(True)
        self.bonus_table.verticalHeader().setVisible(False)
        self.bonus_table.verticalHeader().setStretchLastSection(False)
        self.horizontalLayout_15.addWidget(self.bonus_table)
        self.verticalLayout_5.addWidget(self.row_8)
        self.stackedWidget.addWidget(self.bonus_data_page)
        
        self.customer_data_page = SoldTo_Functions()
        self.stackedWidget.addWidget(self.customer_data_page)

        self.verticalLayout_15.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.pagesContainer)
        self.extraRightBox = QtWidgets.QFrame(self.content)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.themeSettingsTopDetail = QtWidgets.QFrame(self.extraRightBox)
        self.themeSettingsTopDetail.setMaximumSize(QtCore.QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QtWidgets.QFrame.Raised)
        self.themeSettingsTopDetail.setObjectName("themeSettingsTopDetail")
        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)
        self.contentSettings = QtWidgets.QFrame(self.extraRightBox)
        self.contentSettings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.contentSettings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentSettings.setObjectName("contentSettings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.contentSettings)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_7.addWidget(self.contentSettings)
        self.horizontalLayout_4.addWidget(self.extraRightBox)
        self.verticalLayout_6.addWidget(self.content)
        self.bottomBar = QtWidgets.QFrame(self.contentBottom)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottomBar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.creditsLabel = QtWidgets.QLabel(self.bottomBar)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_5.addWidget(self.creditsLabel)
        self.version = QtWidgets.QLabel(self.bottomBar)
        self.version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.version.setObjectName("version")
        self.horizontalLayout_5.addWidget(self.version)
        self.frame_size_grip = QtWidgets.QFrame(self.bottomBar)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_5.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.bottomBar)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.appMargins.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toggleButton.setText(_translate("MainWindow", "Hide"))
        self.btn_home.setText(_translate("MainWindow", "Home"))
        self.btn_bonuses.setText(_translate("MainWindow", "Bonuses"))
        self.btn_invoices.setText(_translate("MainWindow", "Invoices"))
        self.btn_customers.setText(_translate("MainWindow", "Customers"))
        self.btn_products.setText(_translate("MainWindow", "Products"))
        self.titleRightInfo.setText(_translate("MainWindow", "Bonus Program APP"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))

        self.product_data_page.label_5.setText(_translate("MainWindow", "Product Data"))
        self.product_data_page.prod_filter_btn.setText(_translate("MainWindow", "Filter"))
        self.product_data_page.prod_update_btn.setText(_translate("MainWindow", "Update"))
        self.product_data_page.prod_table.setSortingEnabled(True)
        item = self.product_data_page.prod_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Material"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Sal.Prod code"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name code"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Gr code"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Material Name"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Sal.Prod Name"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Family name"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "UoM"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Volume"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Pack type"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Status"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Prod LoB"))
        item = self.product_data_page.prod_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Exclusion"))
        self.product_data_page.prod_file_path_lable.setText(_translate("MainWindow", "File Path"))
        self.product_data_page.open_prod_file_btn.setText(_translate("MainWindow", "Open"))
        self.product_data_page.upload_prod_file_btn.setText(_translate("MainWindow", "Upload"))

        self.label_4.setText(_translate("MainWindow", "Bonus Data"))
        self.bonus_list_edit_btn.setText(_translate("MainWindow", "Edit"))
        self.bonus_list_new_btn.setText(_translate("MainWindow", "New"))
        self.bonus_list_filter_btn.setText(_translate("MainWindow", "Filter"))
        self.bonus_list_down_btn.setText(_translate("MainWindow", "Download"))
        self.bonus_list_del_btn.setText(_translate("MainWindow", "Delete"))
        self.bonus_table.setSortingEnabled(True)
        item = self.bonus_table.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bonus_table.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bonus_table.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bonus_table.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.bonus_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Status"))
        item = self.bonus_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.bonus_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Contract N"))
        item = self.bonus_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "SAP Bonus N"))
        item = self.bonus_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Sold-To"))
        item = self.bonus_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Customer Name"))
        item = self.bonus_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Valid From"))
        item = self.bonus_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Valid To"))

        self.customer_data_page.label.setText(_translate("MainWindow", "Customer Data"))
        self.customer_data_page.label_2.setText(_translate("MainWindow", "Sold-To Data"))
        self.customer_data_page.soldto_edit_btn.setText(_translate("MainWindow", "Edit"))
        self.customer_data_page.soldto_update_btn.setText(_translate("MainWindow", "Update"))
        self.customer_data_page.soldto_delete_btn.setText(_translate("MainWindow", "Delete"))
        self.customer_data_page.soldto_add_btn.setText(_translate("MainWindow", "Create"))
        self.customer_data_page.soldto_filter_btn.setText(_translate("MainWindow", "Filter"))
        self.customer_data_page.soldto_table.setSortingEnabled(True)
        item = self.customer_data_page.soldto_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sold-To"))
        item = self.customer_data_page.soldto_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Customer Name (en)"))
        item = self.customer_data_page.soldto_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Customer Name (ru)"))
        self.customer_data_page.label_3.setText(_translate("MainWindow", "Ship-To Data"))
        self.customer_data_page.shipto_add_btn.setText(_translate("MainWindow", "Create"))
        self.customer_data_page.shipto_edit_btn.setText(_translate("MainWindow", "Edit"))
        self.customer_data_page.shipto_update_btn.setText(_translate("MainWindow", "Update"))
        self.customer_data_page.shipto_delete_btn.setText(_translate("MainWindow", "Delete"))
        self.customer_data_page.shipto_filter_btn.setText(_translate("MainWindow", "Filter"))
        self.customer_data_page.shipto_table.setSortingEnabled(True)
        item = self.customer_data_page.shipto_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ship-To"))
        item = self.customer_data_page.shipto_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Name (en)"))
        item = self.customer_data_page.shipto_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Name (ru)"))
        self.customer_data_page.cust_file_path_lable.setText(_translate("MainWindow", "File Path"))
        self.customer_data_page.open_file_btn.setText(_translate("MainWindow", "Open"))
        self.customer_data_page.upload_file_btn.setText(_translate("MainWindow", "Upload"))
        self.creditsLabel.setText(_translate("MainWindow", "By: Fokina Maria"))
        self.version.setText(_translate("MainWindow", "v1.0.3"))
